import enUS from './en-US';

const trTR: typeof enUS = {
  tabs: { browse: 'Göz At', discover: 'Keşfet', library: 'Kitaplık', profile: 'Profil' },
  common: { save: 'Kaydet', cancel: 'İptal', back: 'Geri', reset: 'Sıfırla', apply: 'Uygula', edit: 'Düzenle', delete: 'Sil', loading: 'Yükleniyor...', search: 'Ara', signIn: 'Giriş yap' },
  languages: { title: 'Dil', subtitle: 'Bu sayfada dili önizle. SwipeLog’un tamamına uygulamak için Kaydet’e dokun.', english: 'İngilizce', turkish: 'Türkçe', spanish: 'İspanyolca', korean: 'Korece', arabic: 'Arapça', portuguese: 'Portekizce', japanese: 'Japonca', russian: 'Rusça', german: 'Almanca', french: 'Fransızca' },
  browse: { searchPlaceholder: 'Film ara', bestMatch: 'En iyi eşleşme', topRated: 'En yüksek puan', newest: 'En yeni', saved: 'Kaydedilenler', watchlist: 'İzleme listesi', trending: 'Trendler', today: 'Bugün', thisWeek: 'Bu hafta', tonightPick: 'Bu gecenin seçimi', tonightPickSubtitle: 'İzleme listenden güçlü bir seçenek', madeForYou: 'Sana özel', madeForYouSubtitle: 'Puanların, favorilerin ve keşif seçimlerinle sıralandı', recentlyLogged: 'Son kaydettiklerin', recentlyLoggedSubtitle: 'En yeni günlük hareketlerin', recentlyAddedWatchlist: 'İzleme listesine son eklenenler', nowPlaying: 'Vizyondakiler', upcoming: 'Yaklaşan filmler', ranked: 'Sıralı filmler', searchEmptyTitle: 'Ne arıyorsun?', searchEmptySubtitle: 'Arama TMDB ile desteklenir', refreshFailed: 'Yenileme başarısız. Tekrar denemek için aşağı çek.', searchFailed: 'Arama başarısız. Lütfen tekrar dene.', noResults: '"{query}" için film bulunamadı.', noFilteredResults: '"{query}" için {filter} sonucu yok.', showAllResults: 'Tüm sonuçları göster', resultsCount: '{count} sonuç', resetFilter: 'Sıfırla', fromWatchlist: 'İzleme listenden', watchlistReady: 'İzlenmemiş kayıtların arasındaki en güçlü seçenek hazır.', addedDate: '{date} eklendi', inWatchlist: 'İzleme listende', releaseTba: 'Vizyon tarihi belli değil', watchedDate: '{date} izlendi' },
  activity: { title: 'Aktivite', subtitle: 'Arkadaş istekleri ve izleme listesi vizyon güncellemeleri', unread: '{count} yeni güncelleme', signInTitle: 'Aktivite için giriş yap', signInDescription: 'Arkadaş istekleri ve sosyal güncellemeler giriş yaptıktan sonra burada görünür.', emptyTitle: 'Henüz aktivite yok', emptyDescription: 'Arkadaş istekleri, yeni arkadaşlıklar ve izleme listesi vizyonları burada görünecek.', newFriendRequest: 'Yeni arkadaş isteği', friendRequestBody: '{name} seninle bağlantı kurmak istiyor.', nowFriends: 'Artık arkadaşsınız', nowFriendsBody: '@{username} profilini aç veya ortak izleme listesi başlat.', movieReleased: '{title} çıktı', movieReleasedBody: 'İzleme listendeki bir film {date} tarihinde vizyona girdi.', releasedDate: '{date} tarihinde çıktı', accept: 'Kabul et', decline: 'Reddet', loadError: 'Aktivite yüklenemedi.', acceptError: 'Arkadaş isteği kabul edilemedi.', declineError: 'Arkadaş isteği reddedilemedi.', open: 'Aktiviteyi aç', unreadA11y: '{count} okunmamış aktivite' },
  profile: { editProfile: 'Profili Düzenle', edit: 'Düzenle', setUp: 'Profilini ayarla', addUsername: 'Kullanıcı adı ekle', addBio: 'İnsanlara film zevkini anlatan bir bio ekle.', favoriteFour: 'Favori dörtlü', favoriteFourSubtitle: 'Zevkini en iyi anlatan filmleri öne çıkar.', chooseFavoriteFour: 'Favori dört filmini seç', watched: 'İzlendi', diary: 'Günlük', watchlist: 'Liste', average: 'Ortalama', movies: 'Film', entries: 'Kayıt', outOfFive: '5 üzerinden', friends: 'Arkadaşlar', friendsSubtitle: 'Profilini paylaş, istekleri kabul et ve arkadaş profillerini aç.', yourActivity: 'Aktiviten', estimatedTime: 'Tahmini izleme süresi', ratingDistribution: 'Puan dağılımı', favoriteGenres: 'Favori türler', favoriteFilms: 'Favori filmler', viewLogs: 'Kayıtları gör', recentDiaryEntries: 'Son günlük kayıtları', viewDiary: 'Günlüğü gör', recentReviews: 'Son yorumlar', seeAll: 'Tümünü gör', noFavorites: 'Henüz favori işaretlenmedi.', noDiary: 'Henüz günlük kaydı yok.', noReviews: 'Henüz yorum yok. Bir filmi kaydederken not eklediğinde burada görünür.', name: 'İsim', username: 'Kullanıcı adı', bio: 'Bio', yourName: 'Adın', bioPlaceholder: 'Film zevkinden bahset...', changeBanner: 'Banner değiştir', profileImages: 'Profil görselleri', resetPicture: 'Fotoğrafı sıfırla', resetBanner: 'Bannerı sıfırla', choosePictureHint: 'Galerinden fotoğraf seçmek için avatara dokun.', iconAvatar: 'İkon avatar', iconAvatarSubtitle: 'Fotoğraf seçilmediğinde profilinde bu ikon görünür.', avatarIconLabel: 'İkon', avatarColorLabel: 'Renk', smartNotifications: 'Akıllı bildirimler', smartNotificationsSubtitle: 'İzleme listendeki filmler vizyon tarihine geldiğinde hatırlatma al.' },
  library: { logs: 'Kayıtlar', diary: 'Günlük', lists: 'Listeler' },
  dates: { unknownYear: 'Yıl bilinmiyor', releasedOn: '{date} tarihinde vizyona girdi', releasesOn: '{date} tarihinde vizyona girecek', releaseTba: 'Vizyon tarihi henüz açıklanmadı' },
};

export default trTR;
